[tool.cibuildwheel]
build = "3.7 3.8 3.9 3.10 3.11 3.12"
skip = ["pp*", "*-win32", "*-manylinux_i686"]

[tool.cibuildwheel.linux]
before-build = "pip install -r requirements-dev.txt"

[tool.cibuildwheel.macos]
before-build = "pip install -r requirements-dev.txt"

[tool.cibuildwheel.windows]
before-build = "pip install -r requirements-dev.txt"

[tool.cibuildwheel.environment]
CIBUILDWHEEL = "1"
